name: Deploy to main branch

on:
    schedule:
        - cron: '0 0 * * *' # Run at midnight every day
    push:
        branches:
            - main # Trigger on push to main branch
    workflow_dispatch: # Allow manual trigger

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.11'

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt
                  echo "Dependencies installed successfully"

            - name: Set up Google Credentials
              env:
                  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
              run: |
                  echo "Setting up Google credentials..."
                  echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json
                  echo "Credentials file created, size: $(wc -c < credentials.json) bytes"

            - name: Run script to fetch data and build site
              run: |
                  echo "Starting app.py execution..."
                  python app.py
                  echo "App.py completed successfully"
                  echo "Checking if index.html was created:"
                  ls -la index.html
                  echo "File size: $(wc -c < index.html) bytes"
                  echo "File content preview (first 10 lines):"
                  head -10 index.html
                  echo "File content preview (last 10 lines):"
                  tail -10 index.html

            - name: Clean up credentials
              run: |
                  echo "Cleaning up credentials..."
                  rm -f credentials.json
                  echo "Credentials cleaned up"

            - name: Commit and Push changes to main
              run: |
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "GitHub Actions"
                  git add index.html  # Thêm file HTML đã tạo vào staging
                  if ! git diff --cached --quiet; then
                      git commit -m "Update index.html with latest data from Google Sheets"
                      git push origin main  # Đẩy thay đổi lên nhánh main
                      echo "Changes committed and pushed to main branch"
                  else
                      echo "No changes detected in index.html, skipping commit and push."
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
