name: Deploy to GitHub Pages

on:
    schedule:
        - cron: '0 0 * * *' # Run at midnight every day
    push:
        branches:
            - main # Trigger on push to main branch
    workflow_dispatch: # Allow manual trigger

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.11'

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt
                  echo "Dependencies installed successfully"

            - name: Set up Google Credentials
              env:
                  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
              run: |
                  echo "Setting up Google credentials..."
                  echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json
                  echo "Credentials file created, size: $(wc -c < credentials.json) bytes"

            - name: Run script to fetch data and build site
              run: |
                  echo "Starting app.py execution..."
                  python app.py
                  echo "App.py completed successfully"
                  echo "Checking if index.html was created:"
                  ls -la index.html
                  echo "File size: $(wc -c < index.html) bytes"
                  echo "File content preview (first 10 lines):"
                  head -10 index.html
                  echo "File content preview (last 10 lines):"
                  tail -10 index.html

            - name: Clean up credentials
              run: |
                  echo "Cleaning up credentials..."
                  rm -f credentials.json
                  echo "Credentials cleaned up"

            - name: Prepare files for deployment
              run: |
                  echo "Files in current directory:"
                  ls -la
                  echo "Creating deployment directory:"
                  mkdir -p deploy
                  cp index.html deploy/
                  cp .nojekyll deploy/
                  if [ -d "images" ]; then
                      cp -r images deploy/
                      echo "Images directory copied"
                  fi
                  if [ -d "templates" ]; then
                      cp -r templates deploy/
                      echo "Templates directory copied"
                  fi
                  echo "Files in deploy directory:"
                  ls -la deploy/
                  echo "Deploy directory size: $(du -sh deploy/)"

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              if: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./deploy
                  publish_branch: gh-pages
                  force_orphan: true
                  user_name: 'github-actions[bot]'
                  user_email: 'github-actions[bot]@users.noreply.github.com'
                  commit_message: 'Deploy: Update certificates with latest data from Google Sheets'
